apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-user: cG9zdGdyZXM=
  postgres-password: cG9zdGdyZXM=
  postgres-db: cG9zdGdyZXM=
  postgres-url: cG9zdGdyZXNxbCtwc3ljb3BnMjovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzLXNlcnZpY2U6NTQzMi9wb3N0Z3Jlcw==
